radicals = [
    {"radical": "一", "meaning": "nhất (số một)", "pinyin": "yī"},
    {"radical": "丨", "meaning": "cổn (nét sổ)", "pinyin": "gǔn"},
    {"radical": "丶", "meaning": "chủ (nét chấm)", "pinyin": "zhǔ"},
    {"radical": "丿", "meaning": "phiệt (nét phẩy)", "pinyin": "piě"},
    {"radical": "乙", "meaning": "ất (vị trí thứ hai)", "pinyin": "yǐ"},
    {"radical": "亅", "meaning": "quyết (nét móc)", "pinyin": "jué"},
    {"radical": "二", "meaning": "nhị (số hai)", "pinyin": "èr"},
    {"radical": "亠", "meaning": "đầu (không có nghĩa)", "pinyin": "tóu"},
    {"radical": "人 (亻)", "meaning": "nhân (người)", "pinyin": "rén"},
    {"radical": "儿", "meaning": "nhi (con trai, trẻ con)", "pinyin": "ér"},
    {"radical": "入", "meaning": "nhập (vào)", "pinyin": "rù"},
    {"radical": "八 (丷)", "meaning": "bát (số tám)", "pinyin": "bā"},
    {"radical": "冂",
        "meaning": "quynh (vùng biên giới xa)", "pinyin": "jiōng"},
    {"radical": "冖", "meaning": "mịch (trùm khăn lên)", "pinyin": "mì"},
    {"radical": "冫", "meaning": "băng (nước đá)", "pinyin": "bīng"},
    {"radical": "几", "meaning": "kỷ (ghế dựa)", "pinyin": "jī"},
    {"radical": "凵", "meaning": "khảm (há miệng)", "pinyin": "kǎn"},
    {"radical": "刀 (刂)", "meaning": "đao (con dao, cây đao)", "pinyin": "dāo"},
    {"radical": "力", "meaning": "lực (sức mạnh)", "pinyin": "lì"},
    {"radical": "勹", "meaning": "bao (bao bọc)", "pinyin": "bāo"},
    {"radical": "匕", "meaning": "chuỷ (cái thìa)", "pinyin": "bǐ"},
    {"radical": "匚", "meaning": "phương (tủ đựng)", "pinyin": "fāng"},
    {"radical": "匸", "meaning": "hệ (che đậy, giấu giếm)", "pinyin": "xì"},
    {"radical": "十", "meaning": "thập (số mười)", "pinyin": "shí"},
    {"radical": "卜", "meaning": "bốc (xem bói)", "pinyin": "bǔ"},
    {"radical": "卩", "meaning": "tiết (đốt tre)", "pinyin": "jié"},
    {"radical": "厂", "meaning": "hán (sườn núi, vách đá)", "pinyin": "hàn"},
    {"radical": "厶", "meaning": "khư, tư (riêng tư)", "pinyin": "sī"},
    {"radical": "又", "meaning": "hựu (lại nữa, một lần nữa)", "pinyin": "yòu"},
    {"radical": "口", "meaning": "khẩu (cái miệng)", "pinyin": "kǒu"},
    {"radical": "囗", "meaning": "vi (vây quanh)", "pinyin": "wéi"},
    {"radical": "土", "meaning": "thổ (đất)", "pinyin": "tǔ"},
    {"radical": "士", "meaning": "sĩ (kẻ sĩ)", "pinyin": "shì"},
    {"radical": "夂", "meaning": "trĩ (đến ở phía sau)", "pinyin": "zhǐ"},
    {"radical": "夊", "meaning": "tuy (đi chậm)", "pinyin": "suī"},
    {"radical": "夕", "meaning": "tịch (buổi tối)", "pinyin": "xī"},
    {"radical": "大", "meaning": "đại (to lớn)", "pinyin": "dà"},
    {"radical": "女",
        "meaning": "nữ (nữ giới, con gái, đàn bà)", "pinyin": "nǚ"},
    {"radical": "子", "meaning": "tử (con)", "pinyin": "zǐ"},
    {"radical": "宀", "meaning": "miên (mái nhà, mái che)", "pinyin": "mián"},
    {"radical": "寸",
        "meaning": "thốn (đơn vị «tấc», đo chiều dài)", "pinyin": "cùn"},
    {"radical": "小 (⺌)", "meaning": "tiểu (nhỏ bé)", "pinyin": "xiǎo"},
    {"radical": "尢 (尣)", "meaning": "uông (yếu đuối)", "pinyin": "wāng"},
    {"radical": "尸", "meaning": "thi (xác chết, thây ma)", "pinyin": "shī"},
    {"radical": "屮",
        "meaning": "triệt (mầm non, cỏ non mới mọc)", "pinyin": "chè"},
    {"radical": "山", "meaning": "sơn (núi)", "pinyin": "shān"},
    {"radical": "川 (巛)", "meaning": "xuyên (sông ngòi)", "pinyin": "chuān"},
    {"radical": "工",
        "meaning": "công (người thợ, công việc)", "pinyin": "gōng"},
    {"radical": "己", "meaning": "kỷ (bản thân mình)", "pinyin": "jǐ"},
    {"radical": "巾", "meaning": "cân (cái khăn)", "pinyin": "jīn"},
    {"radical": "干", "meaning": "can (thiên can, can dự)", "pinyin": "gān"},
    {"radical": "幺", "meaning": "yêu (nhỏ nhắn)", "pinyin": "yāo"},
    {"radical": "广", "meaning": "nghiễm (mái nhà)", "pinyin": "guǎng"},
    {"radical": "廴", "meaning": "dẫn (bước dài)", "pinyin": "yǐn"},
    {"radical": "廾", "meaning": "củng (chắp tay)", "pinyin": "gǒng"},
    {"radical": "弋", "meaning": "dặc (bắn, chiếm lấy)", "pinyin": "yì"},
    {"radical": "弓", "meaning": "cung (cái cung)", "pinyin": "gōng"},
    {"radical": "彐 (彑)", "meaning": "kệ (đầu con nhím)", "pinyin": "jì"},
    {"radical": "彡", "meaning": "sam (lông tóc dài)", "pinyin": "shān"},
    {"radical": "彳", "meaning": "xích (bước chân trái)", "pinyin": "chì"},
    {"radical": "心 (忄)", "meaning": "tâm (quả tim, tâm trí, tấm lòng)",
     "pinyin": "xīn"},
    {"radical": "戈",
        "meaning": "qua (cây qua, một thứ binh khí dài)", "pinyin": "gē"},
    {"radical": "戶 (戶)", "meaning": "hộ (cửa một cánh)", "pinyin": "hù"},
    {"radical": "手 (扌)", "meaning": "thủ (tay)", "pinyin": "shǒu"},
    {"radical": "支", "meaning": "chi (cành nhánh)", "pinyin": "zhī"},
    {"radical": "攴 (攵)", "meaning": "phộc (đánh khẽ)", "pinyin": "pū"},
    {"radical": "文", "meaning": "văn (văn chương, văn vẻ)", "pinyin": "wén"},
    {"radical": "斗", "meaning": "đẩu (cái đấu để đong)", "pinyin": "dǒu"},
    {"radical": "斤", "meaning": "cân (cái búa, rìu)", "pinyin": "jīn"},
    {"radical": "方", "meaning": "phương (vuông)", "pinyin": "fāng"},
    {"radical": "无", "meaning": "vô (không)", "pinyin": "wú"},
    {"radical": "日", "meaning": "nhật (ngày, mặt trời)", "pinyin": "rì"},
    {"radical": "曰", "meaning": "viết (nói rằng)", "pinyin": "yuē"},
    {"radical": "月", "meaning": "nguyệt (tháng, mặt trăng)", "pinyin": "yuè"},
    {"radical": "木", "meaning": "mộc (gỗ, cây cối)", "pinyin": "mù"},
    {"radical": "欠",
        "meaning": "khiếm (khiếm khuyết, thiếu vắng)", "pinyin": "qiàn"},
    {"radical": "止", "meaning": "chỉ (dừng lại)", "pinyin": "zhǐ"},
    {"radical": "歹", "meaning": "ngạt, đãi (xấu xa, tàn ác)", "pinyin": "dǎi"},
    {"radical": "殳", "meaning": "thù (binh khí, cái gậy)", "pinyin": "shū"},
    {"radical": "毋 (母, ⺟)", "meaning": "vô (đừng)", "pinyin": "wú"},
    {"radical": "比", "meaning": "tỉ (so sánh)", "pinyin": "bǐ"},
    {"radical": "毛", "meaning": "mao (lông)", "pinyin": "máo"},
    {"radical": "氏", "meaning": "thị (họ)", "pinyin": "shì"},
    {"radical": "气", "meaning": "khí (hơi nước)", "pinyin": "qì"},
    {"radical": "水 (氵)", "meaning": "thuỷ (nước)", "pinyin": "shuǐ"},
    {"radical": "火 (灬)", "meaning": "hoả (lửa)", "pinyin": "huǒ"},
    {"radical": "爪 (爫)", "meaning": "trảo (móng vuốt cầm thú)",
     "pinyin": "zhǎo"},
    {"radical": "父", "meaning": "phụ (cha)", "pinyin": "fù"},
    {"radical": "爻", "meaning": "hào (hào trong kinh dịch)", "pinyin": "yáo"},
    {"radical": "爿 (丬)", "meaning": "tường (mảnh gỗ, cái giường)",
     "pinyin": "qiáng"},
    {"radical": "片", "meaning": "phiến (mảnh, tấm, miếng)", "pinyin": "piàn"},
    {"radical": "牙", "meaning": "nha (răng)", "pinyin": "yá"},
    {"radical": "牛 (牜, ⺧)", "meaning": "ngưu (trâu)", "pinyin": "niú"},
    {"radical": "犬 (犭)", "meaning": "khuyển (con chó)", "pinyin": "quǎn"},
    {"radical": "玄",
        "meaning": "huyền (màu đen huyền, huyền bí)", "pinyin": "xuán"},
    {"radical": "玉 (⺩)", "meaning": "ngọc (đá quý, ngọc)", "pinyin": "yù"},
    {"radical": "瓜", "meaning": "qua (quả dưa)", "pinyin": "guā"},
    {"radical": "瓦", "meaning": "ngõa (ngói)", "pinyin": "wǎ"},
    {"radical": "甘", "meaning": "cam (ngọt)", "pinyin": "gān"},
    {"radical": "生",
        "meaning": "sinh (sinh đẻ, sinh sống)", "pinyin": "shēng"},
    {"radical": "用", "meaning": "dụng (dùng)", "pinyin": "yòng"},
    {"radical": "田", "meaning": "điền (ruộng)", "pinyin": "tián"},
    {"radical": "疋 (⺪)", "meaning": "thất (đơn vị đo chiều dài, tấm (vải))",
     "pinyin": "pǐ"},
    {"radical": "疒", "meaning": "nạch (bệnh tật)", "pinyin": "nè"},
    {"radical": "癶",
        "meaning": "bát (gạt ngược lại, trở lại)", "pinyin": "bō"},
    {"radical": "白", "meaning": "bạch (màu trắng)", "pinyin": "bái"},
    {"radical": "皮", "meaning": "bì (da)", "pinyin": "pí"},
    {"radical": "皿", "meaning": "mãnh (bát dĩa)", "pinyin": "mǐn"},
    {"radical": "目", "meaning": "mục (mắt)", "pinyin": "mù"},
    {"radical": "矛", "meaning": "mâu (cây giáo để đâm)", "pinyin": "máo"},
    {"radical": "矢", "meaning": "thỉ (cây tên, mũi tên)", "pinyin": "shǐ"},
    {"radical": "石", "meaning": "thạch (đá)", "pinyin": "shí"},
    {"radical": "示 (礻)", "meaning": "thị (chỉ thị; thần đất)",
     "pinyin": "shì"},
    {"radical": "禸", "meaning": "nhựu (vết chân, lốt chân)", "pinyin": "róu"},
    {"radical": "禾", "meaning": "hoà (lúa)", "pinyin": "hé"},
    {"radical": "穴", "meaning": "huyệt (hang lỗ)", "pinyin": "xué"},
    {"radical": "立", "meaning": "lập (đứng, thành lập)", "pinyin": "lì"},
    {"radical": "竹 (⺮)", "meaning": "trúc (tre trúc)", "pinyin": "zhú"},
    {"radical": "米", "meaning": "mễ (gạo)", "pinyin": "mǐ"},
    {"radical": "糸 (糹)", "meaning": "mịch (sợi tơ nhỏ)", "pinyin": "mì"},
    {"radical": "缶", "meaning": "phẫu (đồ sành)", "pinyin": "fǒu"},
    {"radical": "网 (罒, ⺲, ⺳)", "meaning": "võng (cái lưới)", "pinyin": "wǎng"},
    {"radical": "羊 (⺶, ⺷)", "meaning": "dương (con dê)", "pinyin": "yáng"},
    {"radical": "羽", "meaning": "vũ (lông vũ)", "pinyin": "yǔ"},
    {"radical": "老 (耂)", "meaning": "lão (già)", "pinyin": "lǎo"},
    {"radical": "而", "meaning": "nhi (mà, và)", "pinyin": "ér"},
    {"radical": "耒", "meaning": "lỗi (cái cày)", "pinyin": "lěi"},
    {"radical": "耳", "meaning": "nhĩ (tai)", "pinyin": "ěr"},
    {"radical": "聿 (⺻)", "meaning": "duật (cây bút)", "pinyin": "yù"},
    {"radical": "肉 (⺼)", "meaning": "nhục (thịt)", "pinyin": "ròu"},
    {"radical": "臣", "meaning": "thần (bầy tôi)", "pinyin": "chén"},
    {"radical": "自", "meaning": "tự (tự bản thân, kể từ)", "pinyin": "zì"},
    {"radical": "至", "meaning": "chí (đến)", "pinyin": "zhì"},
    {"radical": "臼", "meaning": "cữu (cái cối giã gạo)", "pinyin": "jiù"},
    {"radical": "舌", "meaning": "thiệt (cái lưỡi)", "pinyin": "shé"},
    {"radical": "舛",
        "meaning": "suyễn (sai suyễn, sai lầm)", "pinyin": "chuǎn"},
    {"radical": "舟", "meaning": "chu (cái thuyền)", "pinyin": "zhōu"},
    {"radical": "艮", "meaning": "cấn (quẻ cấn, dừng lại)", "pinyin": "gèn"},
    {"radical": "色", "meaning": "sắc (màu, dáng vẻ, nữ sắc)", "pinyin": "sè"},
    {"radical": "艸 (艹)", "meaning": "thảo (cỏ)", "pinyin": "cǎo"},
    {"radical": "虍", "meaning": "hổ (vằn vện của con hổ)", "pinyin": "hū"},
    {"radical": "虫", "meaning": "trùng (sâu bọ)", "pinyin": "chóng"},
    {"radical": "血", "meaning": "huyết (máu)", "pinyin": "xuè"},
    {"radical": "行",
        "meaning": "hành (đi, thi hành, làm được)", "pinyin": "xíng"},
    {"radical": "衣 (衤)", "meaning": "y (áo)", "pinyin": "yī"},
    {"radical": "襾 (西, 覀)", "meaning": "á (che đậy, úp lên)", "pinyin": "yà"},
    {"radical": "見", "meaning": "kiến (trông thấy)", "pinyin": "jiàn"},
    {"radical": "角", "meaning": "giác (góc, sừng thú)", "pinyin": "jiǎo"},
    {"radical": "言 (訁)", "meaning": "ngôn (nói)", "pinyin": "yán"},
    {"radical": "谷",
        "meaning": "cốc (thung lũng, khe nước chảy)", "pinyin": "gǔ"},
    {"radical": "豆", "meaning": "đậu (hạt đậu, cây đậu)", "pinyin": "dòu"},
    {"radical": "豕", "meaning": "thỉ (con heo, con lợn)", "pinyin": "shǐ"},
    {"radical": "豸", "meaning": "trãi (loài sâu không chân)", "pinyin": "zhì"},
    {"radical": "貝", "meaning": "bối (vật báu)", "pinyin": "bèi"},
    {"radical": "赤", "meaning": "xích (màu đỏ)", "pinyin": "chì"},
    {"radical": "走 (赱)", "meaning": "tẩu (đi, chạy)", "pinyin": "zǒu"},
    {"radical": "足 (⻊)", "meaning": "túc (chân, đầy đủ)", "pinyin": "zú"},
    {"radical": "身",
        "meaning": "thân (thân thể, thân mình)", "pinyin": "shēn"},
    {"radical": "車", "meaning": "xa (chiếc xe)", "pinyin": "chē"},
    {"radical": "辛", "meaning": "tân (cay, vất vả)", "pinyin": "xīn"},
    {"radical": "辰",
        "meaning": "thìn (nhật thực, thần thời gian)", "pinyin": "chén"},
    {"radical": "辵 (辶⻌⻍)", "meaning": "sước (chợt bước đi chợt dừng lại)",
     "pinyin": "chuò"},
    {"radical": "邑 (⻏)", "meaning": "ấp (vùng đất, đất phong cho quan)",
     "pinyin": "yì"},
    {"radical": "酉", "meaning": "dậu (một trong 12 địa chi)", "pinyin": "yǒu"},
    {"radical": "釆", "meaning": "biện (phân biệt)", "pinyin": "biàn"},
    {"radical": "里", "meaning": "lý (dặm; làng xóm)", "pinyin": "lǐ"},
    {"radical": "金 (釒)", "meaning": "kim (kim loại, vàng)", "pinyin": "jīn"},
    {"radical": "長 (镸)", "meaning": "trường (dài; lớn)", "pinyin": "cháng"},
    {"radical": "門", "meaning": "môn (cửa hai cánh)", "pinyin": "mén"},
    {"radical": "阜 (⻖)", "meaning": "phụ (đống đất, gò đất)", "pinyin": "fù"},
    {"radical": "隶", "meaning": "đãi (kịp, kèm theo)", "pinyin": "lì"},
    {"radical": "隹", "meaning": "chuy (chim đuôi ngắn)", "pinyin": "zhuī"},
    {"radical": "雨", "meaning": "vũ (mưa)", "pinyin": "yǔ"},
    {"radical": "青 (靑)", "meaning": "thanh (màu xanh)", "pinyin": "qīng"},
    {"radical": "非", "meaning": "phi (không)", "pinyin": "fēi"},
    {"radical": "面", "meaning": "diện (mặt, bề mặt)", "pinyin": "miàn"},
    {"radical": "革",
        "meaning": "cách (da thú; thay đổi, cải cách)", "pinyin": "gé"},
    {"radical": "韋", "meaning": "vi (da đã thuộc rồi)", "pinyin": "wéi"},
    {"radical": "韭", "meaning": "phỉ (rau phỉ (hẹ))", "pinyin": "jiǔ"},
    {"radical": "音", "meaning": "âm (âm thanh, tiếng)", "pinyin": "yīn"},
    {"radical": "頁", "meaning": "hiệt (đầu; trang giấy)", "pinyin": "yè"},
    {"radical": "風", "meaning": "phong (gió)", "pinyin": "fēng"},
    {"radical": "飛", "meaning": "phi (bay)", "pinyin": "fēi"},
    {"radical": "食 (飠)", "meaning": "thực (ăn)", "pinyin": "shí"},
    {"radical": "首", "meaning": "thủ (cái đầu)", "pinyin": "shǒu"},
    {"radical": "香",
        "meaning": "hương (mùi hương, hương thơm)", "pinyin": "xiāng"},
    {"radical": "馬", "meaning": "mã (con ngựa)", "pinyin": "mǎ"},
    {"radical": "骨", "meaning": "cốt (xương)", "pinyin": "gǔ"},
    {"radical": "高 (髙)", "meaning": "cao (cao)", "pinyin": "gāo"},
    {"radical": "髟", "meaning": "tiêu (tóc dài; lông)", "pinyin": "biāo"},
    {"radical": "鬥",
        "meaning": "đấu (chống nhau, chiến đấu)", "pinyin": "dòu"},
    {"radical": "鬯", "meaning": "sưởng (rượu tế)", "pinyin": "chàng"},
    {"radical": "鬲",
        "meaning": "cách (tên một con sông xưa; cái đỉnh)", "pinyin": "gé"},
    {"radical": "鬼", "meaning": "quỷ (ma quỷ)", "pinyin": "guǐ"},
    {"radical": "魚", "meaning": "ngư (con cá)", "pinyin": "yú"},
    {"radical": "鳥", "meaning": "điểu (con chim)", "pinyin": "niǎo"},
    {"radical": "鹵", "meaning": "lỗ (đất mặn)", "pinyin": "lǔ"},
    {"radical": "鹿", "meaning": "lộc (con hươu)", "pinyin": "lù"},
    {"radical": "麥", "meaning": "mạch (lúa mạch)", "pinyin": "mài"},
    {"radical": "麻", "meaning": "ma (cây gai)", "pinyin": "má"},
    {"radical": "黃", "meaning": "hoàng (màu vàng)", "pinyin": "huáng"},
    {"radical": "黍", "meaning": "thử (lúa nếp)", "pinyin": "shǔ"},
    {"radical": "黑", "meaning": "hắc (màu đen)", "pinyin": "hēi"},
    {"radical": "黹", "meaning": "chỉ (may áo, thêu áo)", "pinyin": "zhǐ"},
    {"radical": "黽", "meaning": "mãnh (con ếch; cố gắng)", "pinyin": "mǐn"},
    {"radical": "鼎", "meaning": "đỉnh (cái vạc)", "pinyin": "dǐng"},
    {"radical": "鼓", "meaning": "cổ (cái trống)", "pinyin": "gǔ"},
    {"radical": "鼠", "meaning": "thử (con chuột)", "pinyin": "shǔ"},
    {"radical": "鼻", "meaning": "tị (cái mũi)", "pinyin": "bí"},
    {"radical": "齊 (斉)", "meaning": "tề (ngang bằng, cùng nhau)",
     "pinyin": "qí"},
    {"radical": "齒", "meaning": "xỉ (răng)", "pinyin": "chǐ"},
    {"radical": "龍 (竜)", "meaning": "long (con rồng)", "pinyin": "lóng"},
    {"radical": "龜 (亀)", "meaning": "quy (con rùa)", "pinyin": "guī"},
    {"radical": "龠", "meaning": "dược (sáo 3 lỗ)", "pinyin": "yuè"}
]
